language: ruby
rvm:
  - 2.1.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y time libxml-parser-perl libgd2-noxpm-dev
script: bundle exec bin/protk_setup.rb tpp omssa blast msgfplus pwiz
